### ISSUE TITLE
Crear validación de formulario de Registro

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Aliwood#12]
- ### _**Email**_
- Asegurar que esté en formato de correo electrónico válido para fines de recuperación de contraseña.

- ### _**Campos Nombre y Apellido:**_
- No dejar los campos vacíos.
- Permitir solo letras en los campos de Nombre y Apellido.
- Permitir más de una palabra si es necesario.

- ### _**Contraseña:**_
- Asegurarse de que la contraseña tenga al menos 8 caracteres.
- Incluir al menos una letra mayúscula en la contraseña.
- Incluir al menos una letra minúscula en la contraseña.
- Incluir al menos un símbolo en la contraseña.
- Incluir al menos un número en la contraseña.

- ### _**Confirmar Contraseña:**_
- Verificar que el contenido en el campo de Contraseña y el campo de Confirmar Contraseña sea idéntico para validar que la información es correcta.

**_Documentación :_** Proporcionar documentación clara en el código JavaScript

Una vez realizado deberá hacer un commit siguiendo los [Commits Convencionales](https://www.conventionalcommits.org/es/v1.0.0/) y luego crear un tag con el nombre formulario-registro-02.
Hacer el push correspondiente.
Generar la PR y notificar al SM para su revisión.

**Comment by Gabibelt** [comment]
Mati por favor cuando puedas avanzar con esto
