### ISSUE TITLE
Crear validación de formulario de Inicio de Sesión

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Aliwood#13]
-  ### **_Email:_**

- No permitir que el campo esté vacío.
- Realizar una consulta en la base de datos y verificar que el email esté correctamente registrado en la misma. Es decir, verificar que el email ingresado sea igual al email registrado. En caso contrario, informar que el email es incorrecto.
-  ### **_Contraseña:_**

- No permitir que el campo esté vacío.
- Realizar una consulta en la base de datos y verificar que la contraseña ingresada coincida con la contraseña asociada al email ingresado en el campo anterior. En caso contrario, informar que la contraseña es incorrecta.

**_Documentación :_** Proporcionar documentación clara en el código JavaScript

Una vez realizado deberá hacer un commit siguiendo los [Commits Convencionales](https://www.conventionalcommits.org/es/v1.0.0/) y luego crear un tag con el nombre formulario-inicio-sesion-02.
Hacer el push correspondiente.
Generar la PR y notificar al SM para su revisión.

**Comment by Gabibelt** [comment]
Seba como venis con esto?, cualquier duda que tengas avisame

**Comment by SebaLerotich** [comment]
Esta en proceso....
