### ISSUE TITLE
Implementación de Sistema de Navegación por Pestañas en JavaScript (jQuery Opcional)

### ISSUE THREAD

**Issue by PabloYR16** [CodeSystem2022/Aliwood#14]
- Implementar la funcionalidad de cambio de pestaña: Utilizando JavaScript puro (sin bibliotecas externas como jQuery), implementar la lógica que permita cambiar entre las pestañas cuando un usuario hace clic en ellas. Deberíamos poder cambiar de una pestaña a otra sin recargar la página. (Nota: jQuery es opcional y puede usarse si es preferido, pero no es obligatorio para esta tarea).

- Gestionar el contenido de cada pestaña: Asegurarse de que el contenido de cada pestaña se muestre y se oculte correctamente según la pestaña seleccionada. Esto debe hacerse de manera eficiente y sin problemas visuales.

- Manejar eventos de clic de manera adecuada: Asegurarse de que los eventos de clic se manejen de manera eficiente y que se prevenga cualquier comportamiento inesperado.

- Documentación : Proporcionar documentación clara en el código JavaScript 

Una vez realizado deberá hacer un commit siguiendo los [Commits Convencionales](https://www.conventionalcommits.org/es/v1.0.0/) y luego crear un tag con el nombre navegacion-por-pestaña-02.
Hacer el push correspondiente.
Generar la PR y notificar al SM para su revisión.

**Comment by Gabibelt** [comment]
Denu como venis con esto?, cualquier cosa que necesites avisanos
